--테이블을 변경하는 ALTER

CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

--테이블에 열을 추가하는 ADD
ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

--테이블에 열 이름을 변경하는 RENAME
ALTER TABLE EMP_ALTER
   RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

--테이블에 열 자료형을 변경하는 MODIFY
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

--테이블의 특정 열을 삭제할 때 DROP
ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;
