
--DELETE구문

CREATE TABLE EMP_TEMP2
   AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

/*
WHERE 절을 사용하여 데이터 일부분만 삭제하기
*/

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;


/*
서브쿼리를 사용하여 데이터 삭제하기
*/

DELETE FROM EMP_TEMP2
  WHERE EMPNO IN (SELECT E.EMPNO FROM EMP_TEMP2 E, SALGRADE S
                    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                      AND S.GRADE = 3
                      AND DEPTNO = 30);
  SELECT * FROM EMP_TEMP2;


DELETE FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2;  