

CREATE TABLE EMP_HW(
EMPNO NUMBER(4),
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
);

SELECT * FROM EMP_HW;

ALTER TABLE EMP_HW
    ADD BIGO NUMBER(20);
    
DESC EMP_HW;

ALTER TABLE EMP_HW
    MODIFY BIGO NUMBER(30);
    
ALTER TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;


INSERT INTO EMP_HW (EMPNO , ENAME , JOB, MGR, HIREDATE, SAL , COMM , DEPTNO )
SELECT E.EMPNO , E.ENAME , E.JOB , E.MGR , E.HIREDATE, E.SAL M ,E.COMM , E.DEPTNO
FROM EMP E;

SELECT * FROM EMP_HW;


DROP TABLE EMP_HW;

