--EMP 테이블과 DEPT 테이블의 제약 조건 살펴보기

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME , R_OWNER , R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP' , 'DEPT');

SELECT * FROM EMP;

SELECT * FROM DEPT;



--FOREIGN KEY 지정하기

/*CREATE TABLE 테이블 이름(
...(다른 열 정의),
열 자료형 CONSTRAINT [제약 조건 이름] REFERENCES 참조 테이블(참조할 열)
); */

--제약조건 이름 미지정 생성
/*
CREATE TABLE 테이블 이름(
...(다른 열 정의),
열 자료형 REFERENCES 참조 테이블(참조할 열)
);*/

--열을 다 정의한 후에 마지막에 제약조건 지정
/*
CREATE TABLE 테이블 이름(
...(다른 열 정의),
CONSTRAINT [제약 조건 이름] FOREIGN KEY(열)
REFERENCES 참조 테이블(참조할 열)
);*/

--DEPT_FK테이블 생성
CREATE TABLE DEPT_FK(
DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
DNAME VARCHAR2(14),
LOC VARCHAR2(13)
);

--EMP_FK테이블 생성
CREATE TABLE EMP_FK(
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
);


INSERT INTO DEPT_FK VALUES (10 , 'TEST_DNAME' ,  'TEST_LOC');

SELECT * FROM DEPT_FK;

INSERT INTO EMP_FK VALUES (9999, 'TEST_NMAME', 'TEST_JOB' , NULL , TO_DATE('2001/01/01' , 'YYYY/MM/DD'), 3000 , NULL ,10);

SELECT * FROM EMP_FK;







--열을 삭제할때 이 데이터를 참조하고 있는 데이터도 삭제

--CONSTRAINT 제약조건명
--FOREIGN KEY (CHILD_TABLE의 FK로 사용할 컬럼명)
--REFERENCES 연결시킬_테이블(연결시킬_테이블의_PK_컬럼명)
--ON DELETE CASCADE

--생성과정이 아닌 ALTER로 테이블에 CASCADE를 설정
--ALTER TABLE EMP_FK ADD CONSTRAINT DEPTFK_DEPTNO_PK REFERENCES DEPT_FK(DEPTNO) ON DELETE CASCADE;



--CASCADE로 FOREIGN KEY설정
--DEPT_FK테이블 생성
CREATE TABLE DEPT_FK2(
DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK2 PRIMARY KEY,
DNAME VARCHAR2(14),
LOC VARCHAR2(13)
);

--EMP_FK테이블 생성
CREATE TABLE EMP_FK2(
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK2 PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK2 REFERENCES DEPT_FK2(DEPTNO) ON DELETE CASCADE
);

INSERT INTO DEPT_FK2 VALUES (10 , 'TEST_DNAME' ,  'TEST_LOC');

SELECT * FROM DEPT_FK2;

INSERT INTO EMP_FK2 VALUES (9999, 'TEST_NMAME', 'TEST_JOB' , NULL , TO_DATE('2001/01/01' , 'YYYY/MM/DD'), 3000 , NULL ,10);

SELECT * FROM EMP_FK2;





SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME , R_OWNER , R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP_FK2' , 'DEPT_FK2');

DELETE FROM DEPT_FK2
WHERE DEPTNO = 10;

------------------------------------
------------------------------------
------------------------------------

CREATE TABLE DEPT_FK3(
DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK3 PRIMARY KEY,
DNAME VARCHAR2(14),
LOC VARCHAR2(13)
);

--EMP_FK테이블 생성
CREATE TABLE EMP_FK3(
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK3 PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK3 REFERENCES DEPT_FK3(DEPTNO) ON DELETE SET NULL
);


INSERT INTO DEPT_FK3 VALUES (10 , 'TEST_DNAME' ,  'TEST_LOC');

SELECT * FROM DEPT_FK3;

INSERT INTO EMP_FK3 VALUES (9999, 'TEST_NMAME', 'TEST_JOB' , NULL , TO_DATE('2001/01/01' , 'YYYY/MM/DD'), 3000 , NULL ,10);

SELECT * FROM EMP_FK3;

