
--PIVOT, UNPIVOT 함수

/*
    PIVOT함수는 기존 테이블 행을 열로 바꾼다.
    UNPIVOT함수는 기존 테이블 열을 행으로 바꿔서 출력.
*/

SELECT DEPTNO , JOB , MAX(SAL)
  FROM EMP
GROUP BY DEPTNO , JOB
ORDER BY DEPTNO , JOB;



--PIVOT함수를 사용하여 직책별.부서별 최고 급여를 2차원 표 형태로 출력하기.
SELECT *
  FROM (SELECT DEPTNO , JOB, SAL FROM EMP)
  PIVOT(MAX(SAL)
        FOR DEPTNO IN (10, 20, 30)
        )
ORDER BY JOB;

--PIVOT 함수를 사용하여 부서별.직책별 최고 급여를 2차원 표 형태로 출력하기.
SELECT *
  FROM (SELECT JOB, DEPTNO ,SAL FROM EMP)
  PIVOT(MAX(SAL)
        FOR JOB IN ('CLERK' AS CLERK
                   ,'SALESMAN' AS SALESMAN
                   ,'PRESIDENT' AS PRESIDENT
                   ,'MANAGER' AS MANAGER
                   ,'ANALYST' AS ANALYST)
        )
  ORDER BY DEPTNO;
  
SELECT DEPTNO
      ,MAX(DECODE(JOB, 'CLERK', SAL)) AS "CLERK"
      ,MAX(DECODE(JOB, 'SALESMAN', SAL)) AS "SALESMAN"
      ,MAX(DECODE(JOB, 'PRESIDENT', SAL)) AS "PRESIDENT"
      ,MAX(DECODE(JOB, 'MANAGER', SAL)) AS "MANAGER"
      ,MAX(DECODE(JOB, 'ANALYST', SAL)) AS "ANALYST"
  FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;


SELECT *
  FROM (
  SELECT DEPTNO
      ,MAX(DECODE(JOB, 'CLERK', SAL)) AS "CLERK"
      ,MAX(DECODE(JOB, 'SALESMAN', SAL)) AS "SALESMAN"
      ,MAX(DECODE(JOB, 'PRESIDENT', SAL)) AS "PRESIDENT"
      ,MAX(DECODE(JOB, 'MANAGER', SAL)) AS "MANAGER"
      ,MAX(DECODE(JOB, 'ANALYST', SAL)) AS "ANALYST"
  FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO)
UNPIVOT(
    SAL FOR JOB IN (CLERK, SALESMAN, PRESIDENT, MANAGER, ANALYST))
ORDER BY DEPTNO , JOB;

     