--테이블 이름을 변경하는 RENAME

RENAME EMP_ALTER TO EMP_RENAME;

--SELECT * FROM EMP_ALTER -- ORA-00942 테이블 찾을수 없음 [에러];

SELECT * FROM EMP_RENAME;

--테이블의 데이터를 삭제하는 TRUNCATE

TRUNCATE TABLE EMP_RENAME;
SELECT * FROM EMP_RENAME;


--테이블을 삭제하는 DROP

DROP TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;