--UPDATE구문

--서브쿼리를 사용하여 데이터 수정하기

UPDATE DEPT_TEMP2
    SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO =40;


--열 하나하나를 서브쿼리로 적용하여 수정하는 경우

UPDATE DEPT_TEMP2 SET DNAME= (SELECT DNAME FROM DEPT WHERE DEPTNO = 40), LOC = (SELECT LOC FROM DEPT WHERE DEPTNO =40)
WHERE DEPTNO = 40;

UPDATE DEPT_TEMP2 SET LOC= 'SEOUL' WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME = 'OPERATIONS');
SELECT * FROM DEPT_TEMP2; 

