--트랜잭션 연습

CREATE TABLE DEPT_TCL
        AS SELECT *
        FROM DEPT;
        
SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

ROLLBACK;

SELECT * FROM DEPT_HW;